services:
  db:
    container_name: postgres
    image: postgres:18-alpine 
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ny_taxi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ny_taxi_password}
      POSTGRES_DB: ${POSTGRES_DB:-ny_taxi}
    ports:
      - '5433:5432'
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    networks:
      - taxi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ny_taxi_user} -d ${POSTGRES_DB:-ny_taxi}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False' 
    ports:
      - "8080:80"
    volumes:
      - ny_taxi_pgadmin_data:/var/lib/pgadmin
    networks:
      - taxi_network
    depends_on:
      db:
        condition: service_healthy

  ingest:
    container_name: taxi_ingest_script
    build: .
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-ny_taxi_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ny_taxi_password}
      - POSTGRES_DB=${POSTGRES_DB:-ny_taxi}
      - POSTGRES_HOST=db       
      - POSTGRES_PORT=5432     # internal port within the network
    volumes:
      - ./data:/app/data       # maps local data folder
    networks:
      - taxi_network
    depends_on:
      db:
        condition: service_healthy
    command: >
      --taxi_path data/green_tripdata_2025-11.parquet
      --zones_path data/taxi_zone_lookup.csv
      --table_name green_taxi_trips

networks:
  taxi_network:
    driver: bridge

volumes:
  ny_taxi_postgres_data:
    name: ny_taxi_postgres_data
  ny_taxi_pgadmin_data:
    name: ny_taxi_pgadmin_data