services:
  db:
    container_name: postgres
    image: postgres:18-alpine 
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    networks:
      - taxi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False' 
    ports:
      - "8081:80" 
    volumes:
      - ny_taxi_pgadmin_data:/var/lib/pgadmin
    networks:
      - taxi_network
    depends_on:
      db:
        condition: service_healthy
        
  # --- ORCHESTRATOR (Kestra) ---
  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    command: server standalone
    user: "root"
    volumes:
      - kestra_storage:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      # ADC Mounting for Mac/Linux
      - ~/.config/gcloud:/root/.config/gcloud:ro 
    ports:
      - "8080:8080"
    environment:
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCP_GCS_BUCKET: ${GCP_GCS_BUCKET}
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      KESTRA_CONFIGURATION: |
        kestra:
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: /app/storage
          queue:
            type: postgres
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_db:5432/${KESTRA_DB_NAME}
            driverClassName: org.postgresql.Driver
            username: ${KESTRA_DB_USER}
            password: ${KESTRA_DB_PASSWORD}
    networks:
      - taxi_network
    depends_on:
      kestra_db:
        condition: service_healthy

  # --- KESTRA DB ---
  kestra_db:
    image: postgres:18-alpine
    container_name: kestra_db
    environment:
      POSTGRES_USER: ${KESTRA_DB_USER}
      POSTGRES_PASSWORD: ${KESTRA_DB_PASSWORD}
      POSTGRES_DB: ${KESTRA_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KESTRA_DB_USER} -d ${KESTRA_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - taxi_network

  # --- INGESTION WORKER ---
  ingest:
    container_name: taxi_ingest_script
    build: .
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db       
      - POSTGRES_PORT=5432     
    volumes:
      - ${LOCAL_DATA_PATH:-./data}:/app/data       
    networks:
      - taxi_network
    depends_on:
      db:
        condition: service_healthy

networks:
  taxi_network:
    driver: bridge

volumes:
  ny_taxi_postgres_data:
  ny_taxi_pgadmin_data:
  kestra_storage: